package classes;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author estagio5
 */
public class telaJokenpo extends javax.swing.JFrame {

    /**
     * Creates new form telaJokenpo
     */
    public telaJokenpo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        resultadoLbl = new javax.swing.JLabel();
        pedraBtn = new javax.swing.JButton();
        papelBtn = new javax.swing.JButton();
        tesouraBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 496));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/gon.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 120, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 261, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 28, -1, -1));

        resultadoLbl.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        resultadoLbl.setText("Vamos Jogar Janken? ");
        getContentPane().add(resultadoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 450, 40));

        pedraBtn.setText("Pedra");
        pedraBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedraBtnActionPerformed(evt);
            }
        });
        getContentPane().add(pedraBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, -1, -1));

        papelBtn.setText("Papel");
        papelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                papelBtnActionPerformed(evt);
            }
        });
        getContentPane().add(papelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, -1, -1));

        tesouraBtn.setText("Tesoura");
        tesouraBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tesouraBtnActionPerformed(evt);
            }
        });
        getContentPane().add(tesouraBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    public String resultado(String r) {
        /*
        1 - pedra
        2 - papel
        3 - tesoura
        */
        double al = Math.random();
        int alresult = (int) (1+ al *(4-1));
        String retorno;
        String obj = new String();
        switch(alresult)
        {
            case 1:
                obj = this.pedraBtn.getText();
                break;
            case 2:
                obj = this.papelBtn.getText();
                break;
            case 3:
                obj = this.tesouraBtn.getText();
                break;
        }
        if((obj.equals("Papel") && r.equals("Pedra")) || (obj.equals("Pedra") && r.equals("Tesoura")) || (r.equals("Papel") && 
                obj.contains("Tesoura")))
            retorno = "Você Perdeu eu escolhi " + obj;
        else if (r.equals(obj))
            retorno = "Empatamos eu escolhi " + obj;
        else
            retorno = "Você ganhou eu escolhi " + obj;
        return retorno;
    }
    private void pedraBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedraBtnActionPerformed
        // TODO add your handling code here:
        resultadoLbl.setText("");
        resultadoLbl.setText(this.resultado(pedraBtn.getText()));
        papelBtn.requestFocus();
    }                          // TODO add your handling code here://GEN-LAST:event_pedraBtnActionPerformed

    private void papelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_papelBtnActionPerformed
        // TODO add your handling code here:
        resultadoLbl.setText("");
        resultadoLbl.setText(this.resultado(papelBtn.getText()));
        this.tesouraBtn.requestFocus();
    }//GEN-LAST:event_papelBtnActionPerformed

    private void tesouraBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tesouraBtnActionPerformed
        // TODO add your handling code here:
        resultadoLbl.setText("");
        resultadoLbl.setText(this.resultado(tesouraBtn.getText()));
        this.pedraBtn.requestFocus();
    }//GEN-LAST:event_tesouraBtnActionPerformed
                      

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {  
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaJokenpo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaJokenpo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaJokenpo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaJokenpo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaJokenpo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton papelBtn;
    private javax.swing.JButton pedraBtn;
    private javax.swing.JLabel resultadoLbl;
    private javax.swing.JButton tesouraBtn;
    // End of variables declaration//GEN-END:variables
}
